include:
  - 'https://framagit.org/memo-fresques/memo-viewer/-/raw/main/common.gitlab-ci.yml'
  - 'https://framagit.org/Marc-AntoineA/tolgitbot/-/raw/main/tolgee.gitlab-ci.yml'


deploy-app:
  rules:
    - when: never

deploy-admin:
  rules:
    - when: never


translations-pull:
  variables:
    TOLGEE_PULL_USE_MR: false
    TOLGEE_STATE: "TRANSLATED"
  dependencies: []
  needs: []
  before_script:
    - git clone --depth 1 https://framagit.org/memo-fresques/memo-viewer.git/ -b main

translations-push:
  rules:
    - when: never
